### ISSUE TITLE
CommonPasswordsValidator vs PwnedPasswords.Validator

### ISSUE THREAD

**Issue by carnahanliam** [andrewlock/CommonPasswordsValidator#13]
I noticed you have a similar [nuget package](https://www.nuget.org/packages/PwnedPasswords.Validator/) which validates passwords using HaveIBeenPwned API. HaveIBeenPwned say they validate against hundreds of millions of passwords from data breaches, and this package is based on a list 10 million. Can you explain what inspired you to create these two separate packages? Am I safe to assume that using your PwnedPasswords.Validator alone should be secure enough since it uses a larger set of passwords, or would you use both?

I also asked this question in the comment section of your blog post about [creating the common password validator](https://andrewlock.net/creating-a-validator-to-check-for-common-passwords-in-asp-net-core-identity/) but then realized it might be better to reach out here.

**Comment by andrewlock** [comment]
> Can you explain what inspired you to create these two separate packages?

I created this one first, before the PwnedPasswords API was available 😃 

> Am I safe to assume that using your PwnedPasswords.Validator alone should be secure enough

Yep, that will definitely be fine - there's no need for both of them! 😃 

Hope that helps!
