### ISSUE TITLE
.NET 7 and 8 + Localization

### ISSUE THREAD

**Issue by peljoe** [andrewlock/CommonPasswordsValidator#14]
Hi,

Will this package be updated for .net 7/8?

Also I figured out it's easy to change the error message using`services.AddIdentity<ApplicationUser, ApplicationRole>().AddTop100000PasswordValidator<ApplicationUser>(errorMessage: "...")`, would be nice to add it somewhere in the readme!
It would be even better if it was actually localizable, which is not the case sadly.

Thanks for this package, very useful anyway.

**Comment by andrewlock** [comment]
I've just pushed a new version that adds supports for .NET 7 and .NET 8, thanks! 🙂
