### ISSUE TITLE
Not working for Microsoft.AspNetCore.Identity 2.0.0

### ISSUE THREAD

**Issue by kristaffa** [andrewlock/CommonPasswordsValidator#2]
Getting the following after adding code to Startup.cs

services.AddIdentity<ApplicationUser, IdentityRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders()
                .AddTop100000PasswordValidator<ApplicationUser>();

Reference to type 'IdentityBuilder' claims it is defined in 'Microsoft.AspNetCore.Identity', but it could not be found

**Comment by BlueNinjaSoftware** [comment]
I had the same issue with the version on NuGet, however building from source includes #1 which seems to resolve the issue. Until the NuGet is updated, you can build and reference the assembly locally.

**Comment by andrewlock** [comment]
Oops, there was an issue in the build script that meant the NuGet didn't get pushed correctly
I've just pushed an update to NuGet which should solve your problem (1.2.1)

**Comment by BlueNinjaSoftware** [comment]
Thanks!

**Comment by kristaffa** [comment]
great thanks!
