### ISSUE TITLE
Support Customizing The Error Message?

### ISSUE THREAD

**Issue by taylorchasewhite** [andrewlock/CommonPasswordsValidator#8]
Andrew--thanks for the work with this. My cofounder and I are working on a company and we like the validator you put together, but would like to change the error message to be a bit more descriptive. Are you open to:

1. Changing the error message
2. Adding a configuration option to support _overriding_ the error message.

If the former, our proposed language is "This password is found in a list of commonly used passwords and cannot be used."

**Comment by taylorchasewhite** [comment]
@excelkobayashi, FYI.

**Comment by andrewlock** [comment]
Hi @taylorchasewhite, that sounds like a good idea 🙂  I've added support for it in #9, I'll look at getting a new version pushed out soon!

**Comment by andrewlock** [comment]
I just pushed out version 1.4.0 with the ability to customise the error message. Enjoy!
